# Generated by Django 5.2.6 on 2025-10-10 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0002_casedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDetails',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='statement',
            name='dob',
            field=models.DateField(default="2000-12-15"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_location',
            field=models.CharField(default='Kenya', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='Morning', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('murder', 'Murder'), ('abuse', 'Child Abuse'), ('accident', 'Accident')], default='Theft', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='suspect_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statement',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statement',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statement',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
