# Generated by Django 5.2.6 on 2025-10-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0003_delete_casedetails_remove_statement_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
