# Generated by Django 5.2.6 on 2025-10-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0006_statement_service_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='Service_no',
            new_name='service_no',
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_evidence',
            field=models.FileField(default='', upload_to='evidence/'),
            preserve_default=False,
        ),
    ]
